q and a models with tests
Seventhstar/qna_7thstar pull request #1
Opened 2017-08-21 14:08 UTC by Seventhstar

2017-08-21 17:40 UTC, darialapina requested changes

2017-08-21 17:40 UTC, darialapina commented on app/models/question.rb
> +  has_many :answers
Тут нужно добавить опцию, чтобы при удалении вопроса удалялись и связанные с ним ответы. И не забудь указать это в тестах, shoulda-matchers умеет это делать (отсутствует dependent: :destroy)

2017-08-21 17:40 UTC, darialapina commented on spec/models/question_spec.rb
> +
Нужен тест на ассоциацию.

2017-08-21 17:40 UTC, darialapina commented on db/migrate/20170821135458_create_answers.rb
> +class CreateAnswers < ActiveRecord::Migration[5.1]
Что-то намудрил с миграциями. 
Зачем две для вопросов?

2017-08-21 19:11 UTC, Seventhstar commented on db/migrate/20170821135458_create_answers.rb
> +class CreateAnswers < ActiveRecord::Migration[5.1]
не понравился 1й вариант как написал и не закоммитил --all, а видимо только git add . сделал - старый файл не удалилсяю

2017-08-21 19:11 UTC, Seventhstar commented on app/models/question.rb
> +  has_many :answers
действительно ) спасибо!

2017-08-21 19:12 UTC, Seventhstar commented on spec/models/question_spec.rb
> +
готово )

2017-08-22 07:33 UTC, vkurennov approved these changes

2017-08-22 08:26 UTC, merged