oauth with email confirmation
Seventhstar/qna_7thstar pull request #10
Opened 2018-03-28 06:54 UTC by Seventhstar

2018-03-28 08:14 UTC, vkurennov requested changes

2018-03-28 08:14 UTC, vkurennov commented on app/models/user.rb
> +      password = Devise.friendly_token[0, 20]
Можно было бы подумать как избавиться от дублирования, и так избавиться от elsif, а то строки уж сильно похожи

2018-03-28 08:14 UTC, vkurennov commented on app/models/user.rb
> +  def confirmation(token)
зачем оставлять пустой метод?

2018-03-28 08:14 UTC, vkurennov commented on config/environments/production.rb
> +  OmniAuth.config.test_mode == true
Зачем тут сравнение? Ну и тестовый режим для разработки не надо включать, так ведь не будет запросов к провайдеру. Нужно это только в тестовой среде делать

2018-03-28 08:14 UTC, vkurennov commented on spec/rails_helper.rb
> +OmniAuth.config.test_mode = true
Вот здесь достаточно этой строки

2018-03-28 08:14 UTC, vkurennov commented on app/models/user.rb
> +  def self.find_for_oauth(auth)
Где тесты модели для этого и других методов?

2018-03-28 08:14 UTC, vkurennov commented on spec/acceptance/oauth/authenticate_with_oauth_spec.rb
> +    scenario 'New user logs in with twitter' do
Нужен еще сценарий, проверяющий, что юзер попытался залогиниться, ввел email, но не подтвердил его. И если он вновь пытается войти через твиттер, то система его не пускает.

2018-03-28 09:07 UTC, Seventhstar commented on config/environments/production.rb
> +  OmniAuth.config.test_mode == true
да ))

2018-03-28 09:09 UTC, Seventhstar commented on app/models/user.rb
> +  def self.find_for_oauth(auth)
ага... забыл вернуть, коммит один откатывал.

2018-04-26 09:36 UTC, vkurennov approved these changes

2018-04-28 05:15 UTC, closed without merging