acceptance test task3
Seventhstar/qna_7thstar pull request #3
Opened 2017-08-28 15:38 UTC by Seventhstar

2017-08-28 19:40 UTC, darialapina requested changes

2017-08-28 19:40 UTC, darialapina commented on app/views/questions/show.html.slim
> += render 'answers/form'
Не аутентифицированному пользователю форму ответа можно не показывать

2017-08-28 19:40 UTC, darialapina commented on app/controllers/answers_controller.rb
> +      # render 'questions/show'
Правильнее было бы здесь оставить render, тогда не нужно будет ошибки валидации так странно передавать. В questions/show просто выводить их при рендере.

2017-08-28 19:40 UTC, darialapina commented on app/controllers/questions_controller.rb
> +    @question.user = current_user
Тут можно было сразу @question = current_user.questions.new(question_params).
Красиво =)

2017-08-28 19:40 UTC, darialapina commented on app/controllers/questions_controller.rb
>      if @question.update(question_params)
Если уж решил делать редактирование, то нужно закрыть возможность обновления для не-автора вопроса.
Тоже касается метода edit, не могу там комментировать.

2017-08-28 19:40 UTC, darialapina commented on app/views/answers/_answers.html.slim
> +			tr
Во всем файле отступы скачут.

2017-08-28 19:40 UTC, darialapina commented on app/views/answers/_form.html.slim
> += form_for [@question, Answer.new], remote: true, html: { id: "new_answer"} do |f|
Зачем тебе remote: true ?
Он ведь даже не отрабатывает.
Кстати, form_for итак по-умолчанию даст этой форме id = "new_answer"

2017-08-28 19:40 UTC, darialapina commented on app/views/answers/_form.html.slim
> +    = f.label :Answer, :class => 'control-label col-lg-2'
хм, а к чему теперь этот label привязан?

2017-08-28 19:40 UTC, darialapina commented on app/views/questions/show.html.slim
> +   = render 'answers/answers'
Отступ хромает.

2017-08-28 19:40 UTC, darialapina commented on spec/acceptance/answers/delete_answer_spec.rb
> +    other_user = create(:user)
other_user тут лишний.

2017-08-28 19:40 UTC, darialapina commented on spec/acceptance/auth/sign_in_spec.rb
> +    expect(current_path).to eq new_user_session_path
Раз уж тут используешь путь от devise, не обязательно в routes.rb было свой именованный добавлять)

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
create: Нужен тест в этом контексте на то, что залогиненный пользователь связывается с ответом

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
> +        expect {delete :destroy, params: {question_id: question, id: answer}}.to change(Answer, :count).by(-1)
Ты так создал вопрос и ответ для тестов, что они между собой не связаны. 
Раз этот тест проходит, значит question_id вообще не нужен. Тем более, что ты объявил ресурс shallow.

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path(answer.question)
По описанной причине выше тебе и пришлось брать вопрос через ассоциацию.

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { question_id: question, id: answer } }
хм?

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +    sign_in_user
Нужна проверка, что залогиненный пользователь связывается с новым вопросом

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +    sign_in_user
Нет проверки на авторство вопроса.
Здесь у тебя залогиненный пользователь и вопрос не связаны.

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +    sign_in_user
Нет проверки на авторство вопроса.
Здесь у тебя залогиненный пользователь и вопрос не связаны.

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +        expect{ delete :destroy, params: {id: question}}.to change(Question, :count).by(-1)
Заодно можно проверить, что уменьшается число вопросов у конкретного пользователя.

2017-08-28 19:40 UTC, darialapina commented on spec/controllers/questions_controller_spec.rb
> +      let(:question) { create(:question) }
твой изначальный question итак не принадлежит @user =)

2017-08-28 19:40 UTC, darialapina commented on spec/factories/questions.rb
>      title "MyString"
Ты создал sequence для заголовка и не используешь её, что делает проверки списков вопросов по заголовкам бессмысленными.

2017-08-28 19:40 UTC, darialapina commented on spec/models/user_spec.rb
> +
А где тест на метод `author_of?`

2017-08-29 05:34 UTC, Seventhstar commented on spec/models/user_spec.rb
> +
оп )) добавляю ))

2017-08-29 06:02 UTC, Seventhstar commented on spec/controllers/questions_controller_spec.rb
> +      let(:question) { create(:question) }
готово

2017-08-29 06:03 UTC, Seventhstar commented on spec/controllers/questions_controller_spec.rb
> +        expect{ delete :destroy, params: {id: question}}.to change(Question, :count).by(-1)
логично. готово )

2017-08-29 06:10 UTC, Seventhstar commented on spec/controllers/questions_controller_spec.rb
> +    sign_in_user
так.

2017-08-29 06:49 UTC, Seventhstar commented on app/views/questions/show.html.slim
> +   = render 'answers/answers'
вот что значит, то в sublime то в rubymine ))

2017-08-29 06:50 UTC, Seventhstar commented on app/views/questions/show.html.slim
> += render 'answers/form'
как раз из-за отступа )

2017-08-29 06:53 UTC, Seventhstar commented on app/controllers/questions_controller.rb
> +    @question.user = current_user
действительно ) спасибо )

2017-08-29 07:00 UTC, Seventhstar commented on spec/acceptance/answers/delete_answer_spec.rb
> +    other_user = create(:user)
так точно )

2017-08-29 07:25 UTC, Seventhstar commented on spec/acceptance/auth/sign_in_spec.rb
> +    expect(current_path).to eq new_user_session_path
да вот хотелось короткие пути, интересно для 5х рельс есть ли более краткое решение чем тут:
https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-when-the-user-can-not-be-authenticated
чтобы редиректился потом не на user/sign_in, а сразу на sign_in

2017-08-29 08:14 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      if @question.update(question_params)
Это можно до следующий заданий оставить, там это будет

2017-08-29 08:15 UTC, vkurennov commented on app/views/answers/_answers.html.slim
> +			tr
Ага, в итоге получаем невалидный файл, который потом не будет ренедрится. И будут вопросы "локально работает, на сервере нет". А все из-за неверных отступов. Настрой оба редактора на отступ в 2 пробела, именно пробела, а не таба

2017-08-29 08:16 UTC, vkurennov commented on spec/acceptance/auth/sign_in_spec.rb
> +    expect(current_path).to eq new_user_session_path
Не думаю, что сейчас стоит на это время тратить.

2017-08-29 08:16 UTC, Seventhstar commented on app/controllers/questions_controller.rb
>      if @question.update(question_params)
Тогда пожалуй оставлю )

2017-08-29 08:23 UTC, Seventhstar commented on app/views/answers/_answers.html.slim
> +			tr
готово! package control почему-то отвалился в sublime. переустановил, а не вернул настройки про табы=2 и конвертацию в пробелы

2017-08-29 08:26 UTC, vkurennov requested changes

2017-08-29 08:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
Нельзя делать редирект, если есть ошибки валидации, т.к. потеряется информация и об ошибках и то, что ввел пользователь и у него не будет возможности отредактировать свой ответ.

2017-08-29 08:26 UTC, vkurennov commented on app/views/answers/_answers.html.slim
> +      th= model_class.human_attribute_name(:body)
Лучше используй напрямую класс Answer, нетс смысла вводить переменную

2017-08-29 08:26 UTC, vkurennov commented on app/views/answers/_answers.html.slim
> +      th=t '.actions', :default => t("helpers.actions")
Используй всегда новый стиль хешей - черз двоеточие: `default: t(...)`

2017-08-29 08:26 UTC, vkurennov commented on app/views/answers/_answers.html.slim
> +					= link_to '[x]', answer_path(answer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-d
Используй новый стиль хешей

2017-08-29 08:26 UTC, vkurennov commented on app/views/answers/_answers.html.slim
> +table.table.table-striped
А ты уверен, что таблица - это удобный способ представления ответов? Посмотри на оргинальный stackoverflow. Разве там в таблице ответы выводятся?

2017-08-29 08:26 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { question_id: question, id: answer } }
Да, что ты проверяешь-то? Сделал запрос в expect, а что должно произойти?

2017-08-29 10:43 UTC, Seventhstar commented on app/views/answers/_answers.html.slim
> +table.table.table-striped
нет, совсем не уверен. посмотрел на stackoverflow - таблица только внутри вопроса.
но думаю в след. задании поправлю.
а то, кажется, слишком долго вожусь с этой задачкой, хотя вроде еще ничего сложного ведь...

2017-08-29 14:31 UTC, vkurennov requested changes

2017-08-29 14:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
У нас все ответы на странице вопроса, нам не нужен этот  экшн.

2017-08-29 14:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [:show, :index]
Для ответов не должно быть show и index

2017-08-29 14:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'user tries to delete foreign answer' do
Редирект в этом контексте тоже надо провреить

2017-08-29 14:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'auth.user tries to delete foreign question' do
Тут нужен тест на редирект

2017-08-29 14:31 UTC, vkurennov commented on spec/factories/questions.rb
>      title "MyString"
Это не исправлено

2017-08-29 14:31 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'should return true if user owns the answer' do
Не нужно со всеми типами аргументов тестировать метод - он же универсальный, достаточно, только на вопросах или на ответах проверить

2017-08-30 08:20 UTC, vkurennov requested changes

2017-08-30 08:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path(answer.question)
Один тест - один expect, это только в acceptance-тестах можно несколько exepct-ов писать

2017-08-30 08:20 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect(response).to redirect_to questions_path
Один тест - один expect, вынести в отдельный тест

2017-08-30 08:20 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe 'author_of?' do
Приехали. А тесты куда делись? Я написал, что не надо и с вопросом и с ответом тестировать, раз метод универсальный. Но с чем-то одним-то надо протестировать.

2017-08-30 08:42 UTC, Seventhstar commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path(answer.question)
ну или видимо простые expect?
т.к. в контроллерах мы писали в прошлом уроке (и скринкасте):
        expect(question.title).to eq 'new title'
        expect(question.body).to eq 'new body'

2017-08-30 09:30 UTC, vkurennov approved these changes

2017-08-31 06:50 UTC, merged