ajax2 test
Seventhstar/qna_7thstar pull request #5
Opened 2017-09-02 16:26 UTC by Seventhstar

2017-09-03 07:47 UTC, vkurennov requested changes

2017-09-03 07:47 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +        id: answer_id
answer_id передается в url, рельсы сами его в парамер добавять, question_id можно получить из вопроса, так что смысла передавать эти данныя в явном виде нет.

2017-09-03 07:47 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      url: "/answers/" + answer_id + "/set_best"
Просто сделай ссылку с remote: true, и укажи method: patch, все будет в разы проще и кода меньше

2017-09-03 07:47 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      success: (data) ->
Если не хочешь делать js-ответ, то тогда повесь на ссылку обработчик на событие 'ajax:success'

2017-09-03 07:47 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      = link_to "set best", set_best_answer_path(answer), class: "set-best-answer btn btn-xs btn-info", remote: true, method: :patch, data: { answer_id: answer.id }, style: 'display:'+(answer.best ?
Здесь же уже все парамтры (и remote и method) прописаны, зачем же перехватывать событие и делать то же самое, что рельсы делают автоматом?

2017-09-03 07:47 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      = link_to "set best", set_best_answer_path(answer), class: "set-best-answer btn btn-xs btn-info", remote: true, method: :patch, data: { answer_id: answer.id }, style: 'display:'+(answer.best ?
Не нужно передвать answer_id в data, он передается в url

2017-09-03 07:47 UTC, vkurennov commented on bash.exe.stackdump
> +Stack trace:
Это что? не храни мусор в репозитории, добавляй его в .gitignore

2017-09-03 13:39 UTC, Seventhstar commented on app/views/answers/_answer.html.slim
> +      = link_to "set best", set_best_answer_path(answer), class: "set-best-answer btn btn-xs btn-info", remote: true, method: :patch, data: { answer_id: answer.id }, style: 'display:'+(answer.best ?
надеюсь правильно понял в чем дело.:
у меня было в контроллере "render json: { message: "You've set the best answer" }"
и поэтому set_best.js.erb не вызывался, только закомментировал - сразу заработало.

2017-09-03 13:42 UTC, Seventhstar commented on app/assets/javascripts/answers.js.coffee
> +      success: (data) ->
ну наверное не нужно, раз переделал на js.erb, но на будущее да, надо туда.
может вообще лучше все сообщения через 'ajax:success'/error делать?

2017-09-04 07:26 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      success: (data) ->
Зависит от задачи, для простых действий и если их немного, js-ответы вполне себе вариант. Про ajax:success мы еще поговорим в следующих уроках

2017-09-04 07:31 UTC, vkurennov approved these changes

2017-09-04 07:31 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +$(document).on 'page:load', ready
Это для старой версии турболинков, в новой нужно только trubolinks:load

2017-09-04 07:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      # render json: { message: "You've set the best answer" }
Удаляй закомментированный код, незачем хранить его в репозитории. И да, дело было именно в этой строке. Ведь ты тут явно указывал, что рендерить, в этом случае вид уже не будет рендерится. Если ничего не указано, то рендерится одноименный вид, совпадающий с типом запроса. Поэтому же не правильно на js-запрос отдавать json.

2017-09-04 07:31 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      = link_to "set best", set_best_answer_path(answer), remote: true, method: :patch, class: "set-best-answer btn btn-xs btn-info", style: 'display:'+(answer.best ? 'none' : '')+ ';'
Для стиля используй двойные кавычки и интерполяцию. Это и короче и более ruby-way.

2017-09-04 07:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    strong= model_class.human_attribute_name(:title) + ':'
В руби принято использовать интерполяцию вместо конкатенации.

2017-09-04 07:31 UTC, vkurennov commented on bash.exe.stackdump
> +Stack trace:
Удали этот файл из репо

2017-09-04 13:34 UTC, merged