Ajax forms
Seventhstar/qna_7thstar pull request #7
Opened 2017-09-10 16:29 UTC by Seventhstar

2017-09-10 18:21 UTC, vkurennov requested changes

2017-09-10 18:21 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      $.ajax
Зачем ты руками отправляешь запрос, когда все делается через `remote: true` в одну строку?

2017-09-10 18:21 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      success: (data) ->
Через json нужно было сделать **только** голосование, остальное работает через js-ответы. Ну даже если и хочешь все сделать через json, то не нужно отправлять запрос из js. Используй `remote: true` и повесь обработчик на ajax:success и ajax:error

2017-09-10 18:21 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $.ajax
Не нужно слать запрос из js

2017-09-10 18:21 UTC, vkurennov commented on config/routes.rb
> +  get 'votes/create'
1. get-запросы никогда не должны ничего изменять на сервере
2. Сделай нормальный ресурс и вложи его в ресурсы вопроса и ответа, тогда в контроллере можно будет динмаически определять родителя и не придется передавать id и тип в параметрах

2017-09-10 18:42 UTC, Seventhstar commented on app/assets/javascripts/answers.js.coffee
> +      $.ajax
видимо, в контексте разговоров о переносе как можно большего на фронт )
надо больше отдыхать )))

2017-09-16 02:45 UTC, vkurennov approved these changes

2017-09-16 07:36 UTC, merged