Action cable
Seventhstar/qna_7thstar pull request #8
Opened 2018-03-12 16:58 UTC by Seventhstar

2018-03-13 08:12 UTC, vkurennov requested changes

2018-03-13 08:12 UTC, vkurennov commented on app/assets/javascripts/channels/answer.coffee
> +      disconnected: ->
Если функция пустая, то зачем ее писать?

2018-03-13 08:12 UTC, vkurennov commented on app/assets/javascripts/channels/answer.coffee
> +        new_answer = $.parseJSON(data)
Вообще-то, данные уже распарсенные должны приходить, если ты их отправляешь как  json, а не как строку

2018-03-13 08:12 UTC, vkurennov commented on app/channels/answer_channel.rb
> +  def subscribed
Этот метод не нужен, достаточно только follow, ведь именно он выполняется при подключении к каналу

2018-03-13 08:12 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        'answers_'+@question.id.to_s,
Используй инетрполяцию в строках, а не конкатенацию. это же руби, а не js

2018-03-13 08:12 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +        'comments_' + get_question_id.to_s, json)
Используй интерполяцию

2018-03-13 08:12 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +    def get_question_id
Стоит сделать более универсальный метод: если у объекта есть метод question_id (определить через respond_to), то вызывать его, если нет, то id. Причем, я бы сделал этот метод в модели Comment и вызывал бы у комментария.

2018-03-13 08:12 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  ul class="Question_#{@question.id}"
не принято html-классы с большой буквы называть

2018-03-13 08:12 UTC, vkurennov commented on app/views/shared/_votes.html.slim
> +- if current_user && !current_user.try(:author_of?,obj)
В руби, начиная с 2.3 появился оператор [safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), поэтому тут можно написать так:
`if !current_user&.author_of?(obj)`

Ну и даже с try первая часть условия теряет смысл, т.к. try как раз и вызовет метод, если приемник метода не nil

2018-03-13 08:12 UTC, vkurennov commented on config/routes.rb
> +    resources :comments, only: [:create]
Вспомни про консерны из прошлого занятия (пересмотри материал по ним) и примени их в роутинге - это очень просто.

2018-03-17 06:16 UTC, Seventhstar commented on app/assets/javascripts/channels/answer.coffee
> +      disconnected: ->
пардон, не удалил ) 
это не я писал, а 'rails g channel'

2018-03-17 08:46 UTC, Seventhstar commented on app/controllers/comments_controller.rb
> +    def get_question_id
да, кстати! ) часто в выборе что в контроллере, что в модель запихать.

2018-03-17 09:10 UTC, Seventhstar commented on app/controllers/answers_controller.rb
> +        'answers_'+@question.id.to_s,
А я тестах сглупил - писал когда 'answers_#{@question.id}'- не сообразил, что ошибка вылезала из-за одинарных кавычек, в двойных все хорошо.

2018-03-17 09:11 UTC, Seventhstar commented on app/controllers/comments_controller.rb
> +        'comments_' + get_question_id.to_s, json)
то же самое )

2018-03-17 12:57 UTC, Seventhstar commented on app/channels/answer_channel.rb
> +  def subscribed
ну да, не почистил после автосоздания.

2018-03-17 12:59 UTC, Seventhstar commented on app/views/shared/_votes.html.slim
> +- if current_user && !current_user.try(:author_of?,obj)
у меня видимо когда полгода назад пробовал - какие-то ошибки были на ruby-2.4, вернулся на 2.2, а так да, такая компактная запись мне попадалась и понравилась )
а первая часть по аналогии с чем-то наверное в спешке зацепил.

2018-03-17 14:37 UTC, Seventhstar commented on config/routes.rb
> +    resources :comments, only: [:create]
применил )

2018-03-18 08:51 UTC, vkurennov approved these changes

2018-03-18 16:20 UTC, merged